config/routes.rb
Rails.application.routes.draw do
  resources :quests do
    put 'toggle', :on => :member
  end
  root 'quests#index'

end

app/models/quest.rb
# == Schema Information
#
# Table name: quests
#
#  id         :integer          not null, primary key
#  name       :text
#  person     :text
#  location   :text
#  notes      :text
#  quest_type :string
#  done       :boolean          default(FALSE)
#  have       :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Quest < ActiveRecord::Base

  scope :done, -> { where(:done => true) }
  scope :current, -> { where(:have => true) }
  scope :unstarted, -> { where(:done => false, :have => false) }
  scope :white_march, -> { where("name ILIKE ?", "%[WM1]%") }

  # Determine if its a quest for white march
  def white_march_part_1?
    name.include?('[WM1]')
  end

  def self.pluck_to_hash(*keys)
    pluck(*keys).map{|pa| Hash[keys.zip(pa)] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: [:show, :edit, :update, :destroy, :toggle]

  # GET /quests
  # GET /quests.json
  def index
    @quests = Quest.all
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = Quest.new(quest_params)

    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end


  def toggle
    if @quest.done
      @quest.update_attributes(:done => false, :have => false)
    elsif @quest.have
      @quest.update_attributes(:done => true, :have => false)
    else
      @quest.update_attributes(:done => false, :have => true)
    end
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /quests/1
  # PATCH/PUT /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to quests_url, notice: 'Quest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quest_params
      params.require(:quest).permit(:name, :person, :location, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quests_helper.rb
module QuestsHelper

  def quest_states
    [
      ['Hide Complete', 'success'],
      ['Hide Current', 'info'],
      ['Hide New', 'default']
    ]
  end

  def set_quest_class(quest, btn=false)
    klass = []
    klass << 'quest' unless btn
    if quest.done
      klass << 'success'
    elsif quest.have
      klass << 'info'
    else
      klass << 'default'
    end
    if !btn && quest.white_march_part_1?
      klass << 'white-march'
    end
    klass.join(' ')
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pillars
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/quests/_form.html.haml
= simple_form_for @quest, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.error_span :name
  = f.input :person
  = f.error_span :person
  = f.input :location
  = f.error_span :location
  = f.input :notes
  = f.error_span :notes
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), quests_path, :class => 'btn btn-default'

app/views/quests/_quest.html.haml
%tr{:class => set_quest_class(quest), :id => "quest_#{quest.id}"}
  %td= link_to quest.id, quest_path(quest)
  %td.quest-attr= quest.name.try(:html_safe)
  %td.quest-attr= quest.person.try(:html_safe)
  %td.quest-attr= quest.location.try(:html_safe)
  %td.quest-attr= quest.notes.try(:html_safe)
  %td= quest.quest_type
  %td
    = link_to toggle_quest_path(quest), :remote => true, :class => "btn btn-#{set_quest_class(quest, true)} toggle-quest", :method => :put do
      %span.show-on-load= icon('spinner', 'Saving', :class => 'fa-spin')
      %span.hide-on-load Toggle

app/views/quests/edit.html.haml
- model_class = Quest
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/quests/index.html.haml
- model_class = Quest
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
  %button.btn.btn-default#whitemarch Hide White March
  - quest_states.each do |state|
    %button.toggle-quest.btn{:data => {:target => state[1]}, :class => "btn-#{state[1]}"}= state[0]
.table-responsive
  %table.table.table-striped#quests
    %thead
      %tr
        %th
          = model_class.human_attribute_name(:id)
          = icon('arrow-up', '', :class => 'up')
          = icon('arrow-down', '', :class => 'down')
        %th
          = model_class.human_attribute_name(:name)
          = icon('arrow-up', '', :class => 'up')
          = icon('arrow-down', '', :class => 'down')
        %th
          = model_class.human_attribute_name(:person)
          = icon('arrow-up', '', :class => 'up')
          = icon('arrow-down', '', :class => 'down')
        %th
          = model_class.human_attribute_name(:location)
          = icon('arrow-up', '', :class => 'up')
          = icon('arrow-down', '', :class => 'down')
        %th
          = model_class.human_attribute_name(:notes)
          = icon('arrow-up', '', :class => 'up')
          = icon('arrow-down', '', :class => 'down')
        %th
          Quest Type
          = icon('arrow-up', '', :class => 'up')
          = icon('arrow-down', '', :class => 'down')
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @quests.each do |quest|
        = render quest

app/views/quests/new.html.haml
- model_class = Quest
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/quests/show.html.haml
- model_class = Quest
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @quest.name
%p
  %strong= model_class.human_attribute_name(:person) + ':'
  %br
  = @quest.person
%p
  %strong= model_class.human_attribute_name(:location) + ':'
  %br
  = @quest.location
%p
  %strong= model_class.human_attribute_name(:notes) + ':'
  %br
  = @quest.notes


= link_to t('.back', :default => t("helpers.links.back")), quests_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_quest_path(@quest), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), quest_path(@quest), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/quests/toggle.js.erb
$('#quest_<%= @quest.id %>').replaceWith("<%=j render @quest %>")